### ISSUE TITLE
[Bug] doesn't work

### ISSUE THREAD

**Issue by tuberry** [lsrdg/vibusen.vim#1]
It shows:
![Screenshot from 2019-11-14 18-14-54](https://user-images.githubusercontent.com/17917040/68848181-db633200-070a-11ea-919f-21a0ce5db28a.png)

**Comment by lsrdg** [comment]
Hey, @Titubery , thanks for the feedback.

I'm not using Ibus these days and I can't really test it. Looking into the code, the variable `s:VibusenDefaultEngine` looks wrong and it was changed to `g:VibusenDefaultEngine` in the last commit. Give it a try if you feel like, any feedback is more than welcome. If you try again, please let me know how it went. But again, it was not tested. Good luck (:

**Comment by tuberry** [comment]
Thanks and sorry for so late response, In `VibusenSetInzsertModePreviousEngine()` if branch, you set ibus engine twice when the first time entering insert mode then the `VibusenCurrentEngine` is non-existed. So I get this:
![image](https://user-images.githubusercontent.com/17917040/69158940-1b1e8500-0b22-11ea-8161-02136bca12fd.png). I fixed that in a way of using EN in normal mode and the other in insert mode. Do you need a pr? @lsrdg

**Comment by lsrdg** [comment]
Hey @tuberry , my turn to apologize for the late reply. (: 

If your fix is working on your end, please send the pull request. As said before, I cannot test it now, but as soon as get Ibus working again I'll we be back on track. I've been missing this functionality quite a lot lately. Hope it keeps working for you.
